import React from 'react';
import { Alert, ScrollView, StatusBar, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useAuthStore } from '../../src/stores/authStore';
import { H, HearthDesign } from '../../src/theme/hearthDesign';
import { ScreenHeader } from '../../src/components/ui/PremiumKit';

export default function PrivacyScreen(){
  const insets=useSafeAreaInsets(); const user=useAuthStore(s=>s.user); const forgot=useAuthStore(s=>s.forgotPassword);
  const reset=()=>Alert.alert('Change password?','Hearth will send a password reset code to your account email.',[{text:'Cancel',style:'cancel'},{text:'Send code',onPress:async()=>{try{await forgot(user?.email||''); Alert.alert('Code sent','Check your email, then continue to the reset screen.',[{text:'Continue',onPress:()=>router.push('/(auth)/reset-password' as any)}]);}catch(e:any){Alert.alert('Could not send code',e?.message||'Please try again.');}}}]);
  return <View style={styles.root}><StatusBar barStyle="dark-content" backgroundColor={H.paper}/><ScrollView contentContainerStyle={{paddingTop:Math.max(insets.top,12),paddingBottom:40}}><ScreenHeader title="Privacy & security" subtitle="Control access to your Hearth account and household data."/><View style={styles.body}>
    <View style={styles.hero}><View style={styles.shield}><Ionicons name="shield-checkmark-outline" size={28} color={H.green}/></View><Text style={styles.heroTitle}>Your household data stays private</Text><Text style={styles.heroSub}>Hearth uses your account and household permissions to decide which data each member can access.</Text></View>
    <Text style={styles.section}>Account security</Text><View style={styles.card}><View style={styles.row}><View style={styles.icon}><Ionicons name="mail-outline" size={18} color={H.navy}/></View><View style={styles.flex}><Text style={styles.title}>Signed-in email</Text><Text style={styles.sub}>{user?.email||'Email unavailable'}</Text></View></View><TouchableOpacity style={[styles.row,styles.border]} onPress={reset}><View style={styles.icon}><Ionicons name="key-outline" size={18} color={H.navy}/></View><View style={styles.flex}><Text style={styles.title}>Change password</Text><Text style={styles.sub}>Send a secure reset code to your email</Text></View><Ionicons name="chevron-forward" size={18} color={H.muted2}/></TouchableOpacity></View>
    <Text style={styles.section}>Data controls</Text><View style={styles.card}><View style={styles.infoRow}><Ionicons name="lock-closed-outline" size={18} color={H.purple}/><Text style={styles.infoText}>Documents, health information and household records are scoped to your household account.</Text></View><View style={[styles.infoRow,styles.border]}><Ionicons name="hardware-chip-outline" size={18} color={H.blue}/><Text style={styles.infoText}>Home Assistant access tokens are used only to connect Hearth to the Home Assistant instance you provide.</Text></View></View>
  </View></ScrollView></View>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:H.paper},body:{paddingHorizontal:18},hero:{borderRadius:24,backgroundColor:H.greenBg,borderWidth:1,borderColor:'#D6EDDE',padding:20,alignItems:'center'},shield:{width:58,height:58,borderRadius:20,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},heroTitle:{color:H.navy,fontSize:17,fontWeight:'900',marginTop:12},heroSub:{color:H.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:5},section:{color:H.navy,fontSize:19,fontWeight:'900',marginTop:25,marginBottom:10},card:{borderRadius:21,backgroundColor:'#fff',borderWidth:1,borderColor:H.lineSoft,overflow:'hidden',...HearthDesign.shadow.card},row:{minHeight:72,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:11},border:{borderTopWidth:1,borderTopColor:H.lineSoft},icon:{width:40,height:40,borderRadius:13,backgroundColor:'#F4F3F3',alignItems:'center',justifyContent:'center'},flex:{flex:1,minWidth:0},title:{color:H.navy,fontSize:13.5,fontWeight:'900'},sub:{color:H.muted,fontSize:10.8,marginTop:2},infoRow:{padding:14,flexDirection:'row',alignItems:'flex-start',gap:10},infoText:{flex:1,color:H.muted,fontSize:11.5,lineHeight:18}});
